Enhanced GitHub Workflow with ARM64 Docker Builds (#173)
* testing the arm workflow

* add param load for docker buildx

* rb for testing

* dry run

* debug docker login in workflow

* fix wrong login flag

* fix dynamic conatiner nameing

* deleted to many lines

* final

* fix small upsi

* run prettier write

* update cache on every commit

* fix yaml error

* export redundant code block to function

* typo

---------

Co-authored-by: Sebastian Knecht <sebastian.knecht@sva.de>

diff --git a/.github/workflows/pkg.yaml b/.github/workflows/pkg.yaml
--- a/.github/workflows/pkg.yaml
+++ b/.github/workflows/pkg.yaml
@@ -7,12 +7,10 @@ on:
   workflow_dispatch: {}
 
 env:
-  app_image: hobbyfarm/ui
-
   should_push_image: |-
     ${{
       github.event_name == 'push' && (
-        github.ref_type == 'tag' ||
+        github.ref_type == 'tag' ||  
         github.ref_name == 'master'
       )
     }}
@@ -23,6 +21,21 @@ env:
       github.ref_type == 'tag'
     }}
 
+  build_and_cache: |-
+    build_and_cache() {
+      arch="$1"
+      if ! docker buildx build \
+        --platform linux/$arch \
+        --cache-from type=local,src=/home/runner/tmp/$arch \
+        --cache-to type=local,dest=/home/runner/tmp/$arch \
+        --tag ${GITHUB_REPOSITORY,,}:$arch \
+        --file Dockerfile . ;
+      then
+        echo "::error::Docker-Build Error. $arch Cache will be deleted now!"
+        rm -rf /home/runner/tmp/$arch/
+      fi
+    }
+
 jobs:
   build:
     name: Build
@@ -31,26 +44,52 @@ jobs:
       - name: Checkout
         uses: actions/checkout@master
 
-      - name: Build container image
-        run: docker build -f Dockerfile -t $app_image:${GIT_COMMIT_SHORT_HASH:-dev} .
+      - name: update cache on every commit
+        uses: actions/cache@v3
+        with:
+          path: /home/runner/tmp
+          key: docker-${{ github.run_id }}
+          restore-keys: |
+            docker-
 
-      - name: Log in container registry
+      - name: Prep build # also builds the conatiner when triggered via workflow_dispatch
+        run: |
+          docker buildx create --use
+          docker buildx inspect --bootstrap
+
+      - name: Fill AMD64 cache
+        run: |
+          ${{ env.build_and_cache }} 
+          build_and_cache amd64
+
+      - name: Fill ARM64 cache
+        run: |
+          ${{ env.build_and_cache }} 
+          build_and_cache arm64
+
+      - name: Login container registry
         if: fromJSON(env.should_push_image)
         run: |
           echo "${{ secrets.REGISTRY_PASSWORD }}" \
             | docker login -u "${{ secrets.REGISTRY_USER }}" --password-stdin
 
-      - name: Push to container registry
+      - name: Build from cache & Push # if commit is taged, the container name is freed from unwanted chars
         if: fromJSON(env.should_push_image)
         run: |
           safe_ref=$(echo "${{ github.ref_name }}" | sed -e 's/[^a-zA-Z0-9\-\.]/-/g')
-          publish_tag=$app_image:$safe_ref
+          docker buildx build --push \
+          --platform linux/amd64,linux/arm64 \
+          --cache-from type=local,src=/home/runner/tmp/amd64 \
+          --cache-from type=local,src=/home/runner/tmp/arm64 \
+          --tag ${GITHUB_REPOSITORY,,}:$safe_ref \
+          --file Dockerfile .
 
-          docker tag $app_image:${GIT_COMMIT_SHORT_HASH:-dev} $publish_tag
-          docker push $publish_tag
-
-      - name: Push latest tag
+      - name: Build from cache & Push latest
         if: fromJSON(env.should_tag_latest)
         run: |
-          docker tag $app_image:${GIT_COMMIT_SHORT_HASH:-dev} $app_image:latest
-          docker push $app_image:latest
+          docker buildx build --push \
+          --platform linux/amd64,linux/arm64 \
+          --cache-from type=local,src=/home/runner/tmp/amd64 \
+          --cache-from type=local,src=/home/runner/tmp/arm64 \
+          --tag ${GITHUB_REPOSITORY,,}:latest \
+          --file Dockerfile .
